// backend/services/jobCardService.js

const repo = require("../repositories/jobCardRepo");

/* ──────────────────────────────────────────────────────────
   Normalise row casing from SQL SPs
────────────────────────────────────────────────────────── */
function normaliseGridRow(row) {
  return {
    uid:           row.UID           ?? row.uid           ?? 0,

    DocNo:         row.DocNo         ?? row.docno         ?? "",
    DocDate:       row.DocDate       ?? row.docdate       ?? null,

    JobName:       row.JobName       ?? row.jobname       ?? "",
    JobDesc:       row.JobDesc       ?? row.jobdesc       ?? "",

    ContactPerson: row.ContactPerson ?? row.contactperson ?? "",
    ContactMobile: row.ContactMobile ?? row.contactmobile ?? null,

    CustomerUid:   row.CustomerUid   ?? row.customeruid   ?? null,

    // ✅ Needed for frontend edit-mode customer display
    Pname:         row.Pname         ?? row.pname         ?? "",
    Pbranch:       row.Pbranch       ?? row.pbranch       ?? "",

    DelivaryDate:  row.DelivaryDate  ?? row.delivarydate  ?? null,

    Active:        row.Active        ?? row.active        ?? 1,
  };
}

/* ──────────────────────────────────────────────────────────
   GET GRID
────────────────────────────────────────────────────────── */
async function getJobCards(active) {
  const data = await repo.getJobCardGrid(active);
  return data.map(normaliseGridRow);
}

/* ──────────────────────────────────────────────────────────
   GET SINGLE FOR EDIT
────────────────────────────────────────────────────────── */
async function getJobCardById(uid) {
  const row = await repo.getJobCardForEdit(uid);

  if (!row) return null;

  return normaliseGridRow(row);
}

/* ──────────────────────────────────────────────────────────
   CREATE
────────────────────────────────────────────────────────── */
async function createJobCard(body, userId) {
  const payload = [
    {
      UID: 0,

      // Auto-generated by SP
      DocNo: "",

      DocDate:       body.DocDate || null,

      JobName:       body.JobName || "",
      JobDesc:       body.JobDesc || "",

      ContactPerson: body.ContactPerson || "",
      ContactMobile: body.ContactMobile ?? null,

      CustomerUid:   body.CustomerUid ?? null,

      DelivaryDate:  body.DelivaryDate || null,

      Active:        body.Active ?? 1,
    },
  ];

  const result = await repo.iudJobCard(JSON.stringify(payload));

  return result[0];
}

/* ──────────────────────────────────────────────────────────
   UPDATE
────────────────────────────────────────────────────────── */
async function updateJobCard(uid, body) {
  const payload = [
    {
      UID: Number(uid),

      // readonly doc no
      DocNo: body.DocNo || "",

      DocDate: body.DocDate || null,

      JobName: body.JobName || "",
      JobDesc: body.JobDesc || "",

      ContactPerson: body.ContactPerson || "",
      ContactMobile: body.ContactMobile ?? null,

      CustomerUid: body.CustomerUid ?? null,

      DelivaryDate: body.DelivaryDate || null,

      Active: body.Active ?? 1,
    },
  ];

  const result = await repo.iudJobCard(JSON.stringify(payload));

  return result[0];
}

/* ──────────────────────────────────────────────────────────
   DELETE
────────────────────────────────────────────────────────── */
async function deleteJobCard(uid) {
  return await repo.deleteRestoreJobCard(Number(uid), 0);
}

/* ──────────────────────────────────────────────────────────
   RESTORE
────────────────────────────────────────────────────────── */
async function restoreJobCard(uid) {
  return await repo.deleteRestoreJobCard(Number(uid), 1);
}

module.exports = {
  getJobCards,
  getJobCardById,
  createJobCard,
  updateJobCard,
  deleteJobCard,
  restoreJobCard,
};